const propiedades = [
    {
        id: 1,
        badge: "RECIÉN PUBLICADO",
        estado: "Disponible",
        titulo: "Casa en Col. Lomas del Guijarro",
        ciudad: "Tegucigalpa",
        departamento: "Francisco Morazán",
        colonia: "Lomas del Guijarro",
        tipo: "Casa",
        preciolps: 3500000,
        preciousd: 140000,
        arvlps: 5000000,
        arvusd: 200000,
        margenlps: 1500000,
        margenusd: 60000,
        repminlps: 250000,
        repmaxlps: 400000,
        repminusd: 10000,
        repmaxusd: 16000,
        habitaciones: 3,
        banos: 2,
        metros: 180,
        lote: 320,
        tipoprop: "Casa Unifamiliar",
        parking: "Cochera doble",
        anoconst: 1998,
        condicion: "Remodelación Media",
        techo: "10+ años",
        hvac: "Aire central",
        hvacedad: "6-10 años",
        cimentacion: "Concreto",
        ocupacion: "Desocupada",
        descripcion: "Excelente oportunidad de inversión en zona exclusiva de Tegucigalpa. Propiedad con estructura sólida, excelente distribución y gran potencial de plusvalía. Ideal para fix & flip o renta de largo plazo. Ubicada en una de las colonias más cotizadas de la capital con fácil acceso a centros comerciales, colegios internacionales y vías principales.",
        comps: [
            { dir: "Col. Lomas del Guijarro, calle principal", lps: 4800000, usd: 192000 },
            { dir: "Col. Lomas del Guijarro Sur", lps: 5100000, usd: 204000 },
            { dir: "Col. Lomas del Mayab", lps: 4900000, usd: 196000 }
        ],
        caracteristicas: "Cochera doble,Jardín amplio,Cisterna propia,Sistema eléctrico nuevo",
        notas: "Fix & flip en zona AAA,Renta estimada L.18,000/mes,Remodelación principalmente cosmética,Zona con alta valorización",
        terminos: "Efectivo | Financiamiento privado",
        emd: "L. 50,000 dentro de 24 hrs",
        cierre: "Mayo 30, 2026",
        dias: 0,
        vistas: 12,
        img: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        imgs: [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80"
        ]
    },
    {
        id: 2,
        badge: "DESTACADO",
        estado: "Disponible",
        titulo: "Apartamento Res. Las Lomas",
        ciudad: "San Pedro Sula",
        departamento: "Cortés",
        colonia: "Residencial Las Lomas",
        tipo: "Apartamento",
        preciolps: 2200000,
        preciousd: 88000,
        arvlps: 3400000,
        arvusd: 136000,
        margenlps: 1200000,
        margenusd: 48000,
        repminlps: 150000,
        repmaxlps: 250000,
        repminusd: 6000,
        repmaxusd: 10000,
        habitaciones: 2,
        banos: 2,
        metros: 95,
        lote: 0,
        tipoprop: "Apartamento",
        parking: "1 espacio asignado",
        anoconst: 2010,
        condicion: "Remodelación Leve",
        techo: "4-10 años",
        hvac: "Mini split",
        hvacedad: "1-5 años",
        cimentacion: "Concreto",
        ocupacion: "Desocupada",
        descripcion: "Apartamento en excelente ubicación en San Pedro Sula con gran potencial de inversión. Edificio seguro con vigilancia 24/7, piscina y áreas comunes. Listo para remodelar y poner en renta o revender con ganancia considerable en una de las zonas de mayor demanda de la ciudad.",
        comps: [
            { dir: "Res. Las Lomas Torre B", lps: 3200000, usd: 128000 },
            { dir: "Res. Villa del Rey SPS", lps: 3500000, usd: 140000 }
        ],
        caracteristicas: "Piscina del edificio,Vigilancia 24/7,Vista a la ciudad,2 habitaciones,2 baños",
        notas: "Renta estimada L.12,000/mes,Alta demanda empresarial,Remodelación rápida 6-8 semanas",
        terminos: "Efectivo | Financiamiento bancario",
        emd: "L. 30,000 dentro de 24 hrs",
        cierre: "Junio 15, 2026",
        dias: 3,
        vistas: 47,
        img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
        imgs: [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"
        ]
    },
    {
        id: 3,
        badge: "EXCLUSIVO",
        estado: "Disponible",
        titulo: "Terreno Comercial Bulevar del Norte",
        ciudad: "San Pedro Sula",
        departamento: "Cortés",
        colonia: "Zona Industrial",
        tipo: "Terreno",
        preciolps: 8500000,
        preciousd: 340000,
        arvlps: 14000000,
        arvusd: 560000,
        margenlps: 5500000,
        margenusd: 220000,
        repminlps: 0,
        repmaxlps: 0,
        repminusd: 0,
        repmaxusd: 0,
        habitaciones: 0,
        banos: 0,
        metros: 1200,
        lote: 1200,
        tipoprop: "Terreno",
        parking: "Área libre",
        anoconst: 0,
        condicion: "Listo para Construir",
        techo: "N/A",
        hvac: "N/A",
        hvacedad: "N/A",
        cimentacion: "N/A",
        ocupacion: "Desocupado",
        descripcion: "Terreno estratégicamente ubicado sobre el Bulevar del Norte en San Pedro Sula. Ideal para desarrollo comercial, bodega industrial o proyecto mixto. Alta visibilidad, acceso de trailer y todos los servicios disponibles. Zona de crecimiento acelerado con alta demanda.",
        comps: [
            { dir: "Bulevar del Norte Km 5", lps: 13500000, usd: 540000 },
            { dir: "Zona Industrial Col. Los Andes", lps: 15000000, usd: 600000 }
        ],
        caracteristicas: "Sobre Bulevar principal,Acceso de trailer,Todos los servicios,Escritura limpia,Uso comercial",
        notas: "Alta rentabilidad para desarrollo,Zona de crecimiento acelerado,Ideal para bodega o comercio",
        terminos: "Efectivo",
        emd: "L. 100,000 dentro de 24 hrs",
        cierre: "Julio 1, 2026",
        dias: 1,
        vistas: 89,
        img: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
        imgs: [
            "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"
        ]
,
    {
        id: 4,
        badge: "Oportunidad",
        estado: "Disponible",
        titulo: "Residencia en Col. Trejo",
        ciudad: "San Pedro Sula",
        departamento: "Cortés",
        colonia: "Col. Trejo",
        tipo: "Casa",
        preciolps: 4200000,
        preciousd: 168000,
        arvlps: 6500000,
        arvusd: 260000,
        margenlps: 2300000,
        margenusd: 92000,
        repminlps: 300000,
        repmaxlps: 500000,
        repminusd: 12000,
        repmaxusd: 20000,
        habitaciones: 4,
        banos: 3,
        metros: 250,
        lote: 450,
        tipoprop: "Casa Unifamiliar",
        parking: "Garaje techado 2 autos",
        anoconst: 1995,
        condicion: "Remodelación Media",
        techo: "8 años",
        hvac: "Splits",
        hvacedad: "2-5 años",
        cimentacion: "Concreto",
        ocupacion: "Propietario",
        descripcion: "Hermosa propiedad en una de las mejores zonas de San Pedro Sula. Amplios espacios, patio grande y estructura en excelentes condiciones. Perfecta para modernizar y revender a precio premium. La Col. Trejo mantiene una de las plusvalías más estables de la ciudad.",
        comps: [
            { dir: "Col. Trejo 2da Etapa", lps: 6200000, usd: 248000 },
            { dir: "Col. Trejo calle principal", lps: 6800000, usd: 272000 }
        ],
        caracteristicas: "Cisterna,Portón eléctrico,Área de lavandería,Cuarto de servidumbre",
        notas: "Zona de alta plusvalía,Estructura sólida,Fácil acceso,Cerca de escuelas",
        terminos: "Efectivo | Crédito Bancario",
        emd: "L. 75,000",
        cierre: "Agosto 15, 2026",
        dias: 2,
        vistas: 34,
        img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        imgs: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80"]
    },
    {
        id: 5,
        badge: "REBAJADO",
        estado: "En Proceso",
        titulo: "Casa en Col. Alameda",
        ciudad: "Tegucigalpa",
        departamento: "Francisco Morazán",
        colonia: "Col. Alameda",
        tipo: "Casa",
        preciolps: 2800000,
        preciousd: 112000,
        arvlps: 4200000,
        arvusd: 168000,
        margenlps: 1400000,
        margenusd: 56000,
        repminlps: 200000,
        repmaxlps: 350000,
        repminusd: 8000,
        repmaxusd: 14000,
        habitaciones: 3,
        banos: 2,
        metros: 160,
        lote: 280,
        tipoprop: "Casa de un nivel",
        parking: "1 vehiculo",
        anoconst: 1985,
        condicion: "Para remodelar",
        techo: "15 años",
        hvac: "No tiene",
        hvacedad: "N/A",
        cimentacion: "Piedra y Concreto",
        ocupacion: "Desocupada",
        descripcion: "Propiedad de un solo nivel ideal para oficinas o vivienda en zona céntrica de Tegucigalpa. Requiere actualización de acabados y sistema eléctrico. Ubicación estratégica cerca de bancos y comercios.",
        comps: [
            { dir: "Col. Alameda calle posterior", lps: 4000000, usd: 160000 },
            { dir: "Col. Miralagos", lps: 4300000, usd: 172000 }
        ],
        caracteristicas: "Un solo nivel,Zona comercial/residencial,Cisterna,Patio pequeño",
        notas: "Ideal para oficina,Remodelación profunda necesaria,Ubicación premium",
        terminos: "Solo Efectivo",
        emd: "L. 100,000",
        cierre: "Septiembre 30, 2026",
        dias: 5,
        vistas: 56,
        img: "https://images.unsplash.com/photo-1513584732867-c475d73ad91f?w=800&q=80",
        imgs: ["https://images.unsplash.com/photo-1513584732867-c475d73ad91f?w=800&q=80"]
    }
];
];
